#! /bin/sh

#Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
picom --experimental-backend &
feh --bg-fill walls/late-summer-evening-in-kotor.png
dunst &

bspc monitor -d I II III IV V VI VII

bspc config border_width         0
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

